app/models.py
from .import db,login_manager
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin

from datetime import datetime

@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))



class User(UserMixin,db.Model):
    
    __tablename__ = 'users'
    
    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255))
    email = db.Column(db.String(255), unique=True, index=True)
    password_hash=db.Column(db.String(255))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    posts =  db.relationship('Post', backref = 'user', lazy = "dynamic")
    Comments = db.relationship('Comment', backref = 'user', lazy = "dynamic")

    
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.password_hash,password)
    

    def __repr__(self):
        return f'User {self.username}'
class Post(db.Model):
    
    __tablename__ = 'posts'
    
    id = db.Column(db.Integer, primary_key = True)
    title = db.Column(db.String(255), index = True)
    body = db.Column(db.String(255), index = True)
    timestamp = db.Column(db.DateTime, index=True, default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    comments = db.relationship('Comment', backref = 'post')
    
    def save_post(self):
        db.session.add(self)
        db.session.commit()
    
    @classmethod 
    def get_posts(cls,id):
        posts = Post.query.filter_by(user_id = id).all()
        return posts

    def __repr__(self):
        return '<Post {}>'.format(self.body)
    
class Comment(db.Model):
    
    __tablename__ = 'comments'
    
    id = db.Column(db.Integer, primary_key = True)
    comment_post = db.Column(db.String(255), index=True)
    time = db.Column(db.DateTime, default=datetime.utcnow)
    post_id = db.Column(db.Integer, db.ForeignKey('posts.id'))
    user_id = db.Column(db.Integer, db.ForeignKey('users.id'))
    
    def save_comments(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comments(cls, id):
        comments = Comment.query.filter_by(post_id=id).all()
        return comments
class Quote:
    def __init__ (self,id,author,quote,permalink):
        self.id =id
        self.author = author 
        self.quote = quote
        self.permalink = permalink

    

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField
from wtforms.validators import Required

class BlogForm(FlaskForm):
    title = StringField('Title',validators=[Required()])
    post = TextAreaField('Blog', validators=[Required()])
    submit = SubmitField('Submit')
    
class CommentsForm(FlaskForm):
    comment = TextAreaField('Comments', validators = [Required()])
    submit = SubmitField('Submit')
    
class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')
    

app/__init__.py
from flask import Flask
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail


# from flask_uploads import UploadSet,configure_uploads,IMAGES

db =SQLAlchemy()
bootstrap = Bootstrap()

mail = Mail()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'
photos = UploadSet('photos',IMAGES)

def create_app(config_name):
    
    app = Flask(__name__)
    
      
    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    
     #Registering the blueprint 
    
    from .main import  main  as main_blueprint
    app.register_blueprint(main_blueprint)
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')
    
    # Initializing flask extensions
    
    db.init_app(app)
    bootstrap.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    
    #setting config
    from .requests import configure_request
    configure_request(app)
    
     # configure UploadSet
    configure_uploads(app,photos)
    
    return app
    

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,errors,forms 

app/main/views.py
from . import main
from flask_login import login_required
from flask import render_template,redirect,url_for,request,abort,flash
from ..models import User,Post,Comment
from flask_login import login_required,current_user
from ..import db,photos
from .forms import BlogForm,CommentsForm,UpdateProfile
from ..requests import get_random_quote


@main.route('/')
def index():
    quote = get_random_quote()
    
    return render_template('index.html',quote = quote)

@main.route('/blogs')
def blogs():
    posts = Post.query.order_by(Post.timestamp.desc()).all()
    
    return render_template('blogs.html',posts=posts)
    
@main.route('/blogs/new/', methods=["GET","POST"])
@login_required
def new_blog():
    '''
    view function that returns the blog form
    '''
    form = BlogForm()
   
    if form.validate_on_submit():
        post = form.post.data
        title = form.title.data
        
        new_post = Post(title=title,body=post,user=current_user)
        new_post.save_post()
        return redirect(url_for('.blogs'))
    
    title='blogs'
    return render_template('new_blog.html',title=title,blog_form=form)

@main.route('/comments/new/<int:id>', methods=["GET","POST"])
@login_required
def comment(id):
    '''
    view function that returns a form to insert a comment on a post
    '''
    
    form = CommentsForm()
    post = Post.query.filter_by(id=id).first()
     
    if form.validate_on_submit():
        comment =  form.comment.data
        new_comment = Comment(post_id = post.id, comment_post=comment,user=current_user)
        new_comment.save_comments()
        
        return redirect(url_for('main.comments', id=post.id))
    
    return render_template('new_comment.html',comment_form=form,post=post)


@main.route('/comments/<int:id>')
def comments(id):
    post = Post.query.get(id)
    comment = Comment.get_comments(post.id)
    return render_template('comments.html', comment = comment,post=post)
    print(comments)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)


@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(username = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route("/post/<int:post_id>/delete", methods=[ 'GET','POST'])
@login_required
def delete_post(post_id):
    
    post = Post.query.get(post_id)
    if post.user != current_user:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Post deleted!', 'success')
    return redirect(url_for('main.blogs'))

app/templates/base.html
{% extends 'bootstrap/base.html'%}


<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/blogs.html
{% extends 'base.html' %}
{% from 'macros.html' import displayBlog with context %}

{% block content %}

<div class="jumbotron" style="background-color: rgb(178, 216, 231)">
    <div class="container-fluid">
        <div class="row" style="font-size: 20px;">
            {% if posts %}
    
            {{ displayBlog(posts)}}
    
            {% else %}
    
            <div class="card" style="width: 100%;">
                <h4 class="text-center">No posts yet click on add to add.</h4>
            </div>
    
            {%  endif %}
    
        </div>
    
    </div>
</div>

{% endblock  %}

app/templates/comments.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}

{% block content %}
<div class="jumbotron jumbotron-fluid" style="background-color: rgb(29, 228, 228)" >
    <div class="legend">
      
        <h3 class="text-center">Comment Logs</h3>
        <hr>
        {% if comment %}
        <div class="row" style="font-size: 27px;">
            {{ macro.displayComments(comment) }}
        </div>
        {% else %}
        <h3 >No comments yet</h3>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}


{% block content %}

<div class="jumbotron jumbotron-fluid">
    <div class="continer-fluid" style="text-align: center;" >
        <div class="row" style="text-align: center;">
            
            <div class="col-sm-12 col-md-6 col-lg-4">
                </di<div class="card" style="width: 18rem;">
                
                <div class="card-body" style="background-color: aquamarine">
                    <h5 class="card-title" style="font-size: 30px;">{{quote.author}}</h5>
                    <small><h6 style="font-size: 30px;" ><b>Random quotes</b></h6></small>
                    <p class="card-text">{{quote.quote}}</p>
                    <a href="{{quote.permalink}}" class="btn btn-sm btn-outline-info" style="font-size: 24px;" >more info</a>
                </div>
            </div>
            
            
            </div>
        </div>
    </div>
    <hr>
</div>

{% endblock %}

app/templates/macros.html
{% macro displayBlog(my_blogs,user) %}
{% for blog in my_blogs %}
<div class="col-md-1"></div>
<div class="col-md-10">
    <div class="card m-3">
        <div class="card-header">
            <h4>{{blog.title}}</h4>
            
        </div>
        <div class="card-body">
            {{blog.body}}
        </div>
        <div class="card-footer">

            <div class="row">
                <div class="col-md-2">
                    <a class="btn btn-sm btn-outline-info" href="/comments/{{blog.id}}">View Comments</a>
                </div>
                <div class="col-md-8"></div>
                <div class="col-md-2">
                    <a class="btn btn-sm btn-outline-danger m-1"
                        href="{{url_for('main.delete_post' , post_id=blog.id)}}">Delete</a>
                    <a class="btn btn-sm btn-outline-info" href="/comments/new/{{blog.id}}">Comment</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="col-md-1"></div>
{% endfor %}
{% endmacro %}

{% macro displayComments(comment_list) %}
{% for comment in comment_list %}

<div class="col-md-6 mb-3">
    <div class="card">
        <div class="card-body">
            <h3>{{comment.comment_post}}</h3>
        </div>
        <div class="card-footer">
            <footer class="blockquote-footer">{{comment.user.username}} commented on your pitch</footer>

        </div>
    </div>
</div>



{% endfor %}
{% endmacro %}

app/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-light"  style="background-color: #94d9db;">
    <a class="navbar-brand" href="/">Navbar</a>
           
    

    <div class="collapse navbar-collapse " class="navbarNavAltMarkup">
        <div class="navbar-nav ">
            
            <a class="nav-link active" style="font-size: 24px;" href="/">Home <span class="sr-only">(current)</span></a>
            <a class="nav-link active" style="font-size: 24px;" href="{{url_for('main.blogs')}}">Blogs</a>
            <a class="nav-link active" style="font-size: 24px;" href="{{url_for('main.new_blog')}}">Add</a>
           
        </div>

        <ul class="nav navbar-nav navbar-right">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" style="font-size: 24px;" href="{{url_for('main.profile',uname=current_user.username)}}"
                    title="profile">{{current_user.username}}</a>

            </li>
            <li class="nav-item">
                <a class="nav-link" style="font-size: 24px;" href="{{url_for('auth.logout')}}">Sign out</a>
            </li>
            {% else %}

            <li class="nav-item">
                <a class="nav-link" style="font-size: 24px;" href="{{url_for('auth.login')}}">Login</a>
            </li>
            {% endif %}
        </ul>

    </div>
</nav>

app/templates/new_blog.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}

<div class="jumbotron jumbotron-fluid" style="background-color:rgb(82, 134, 158)">
    <div class="row" style="font-size: 17px; font-family:'Courier New', Courier, monospace">
        <div class="col-md-2"></div>
        <div class="col-md-8" >
                {{ wtf.quick_form(blog_form) }}
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

{% endblock %}

app/templates/new_comment.html
{% extends 'base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
<div class="jumbotron jumbotron-fluid" style="background-color: rgb(16, 109, 126)">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            {{ wtf.quick_form(comment_form) }}
        </div>
        <div class="col md-2"></div>
    </div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% extends 'base.html' %}
{% import 'macros.html' as macro %}
{% block content %}
<div class="container">
    <div class="row">
        <!--Displaying Username-->
        <div class="col-md-4">
            <h3>{{user.username|capitalize}}</h3>
            <!--Displaying User bio-->
            {% if user.bio %}
            <p>{{user.bio}}</p>

            {%else%}
            <p>{{user.username|capitalize}} has no bio</p>
            {% endif %}

            {% if user == current_user %}
            <a class="btn btn-sm btn-outline-info" href="{{url_for('main.update_profile',uname=user.username)}}">Edit
                profile</a>



            {% endif %}
        </div>
        <!--Displaying pofile photo -->
        <div class="col-md-4">



            {% if user.profile_pic_path %}

            <img class="img-circle" src="{{url_for('static',filename=user.profile_pic_path)}}" alt=""
                class="img-thumbnail" height="200px" width="200px" style="border-radius:50%">

            {%else%}
            <p>No profile picture</p>

            {% endif %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post"
                enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">

            </form>
        </div>
    </div>
</div>

{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
    {{wtf.quick_form(form)}}
</div>
{% endblock %}